import type { DashboardSnapshot } from "./dashboard-types";

export const dashboardSnapshot: DashboardSnapshot = {
  generatedAt: "2026-04-15T22:58:00-07:00",
  dataSource: "snapshot",
  liveStatus: "snapshot-only",
  agentRuns: [
    {
      id: "run-101",
      agent: "planner",
      issueNumber: 412,
      task: "Outline dashboard V3 scaffold",
      status: "done",
      updatedAt: "2026-04-15T22:40:00-07:00",
      source: "snapshot",
    },
    {
      id: "run-102",
      agent: "engineer",
      issueNumber: 417,
      task: "Wire truth-first dashboard shell",
      status: "running",
      updatedAt: "2026-04-15T22:55:00-07:00",
      source: "snapshot",
    },
    {
      id: "run-103",
      agent: "analyst",
      issueNumber: null,
      task: "Review issue labels and blockers",
      status: "blocked",
      updatedAt: "2026-04-15T22:52:00-07:00",
      source: "snapshot",
    },
  ],
  subagentRuns: [
    {
      id: "sub-201",
      parentRunId: "run-102",
      name: "route scaffold",
      task: "Add /dashboard and /issues routes",
      status: "done",
      updatedAt: "2026-04-15T22:54:00-07:00",
    },
    {
      id: "sub-202",
      parentRunId: "run-102",
      name: "snapshot plumbing",
      task: "Load local truth-first data first",
      status: "running",
      updatedAt: "2026-04-15T22:56:00-07:00",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Keep dashboard read-only",
      status: "done",
      issueNumber: 417,
      owner: "engineer",
      updatedAt: "2026-04-15T22:54:00-07:00",
    },
    {
      id: "task-2",
      title: "Expose honest source labels",
      status: "in_progress",
      issueNumber: 417,
      owner: "engineer",
      updatedAt: "2026-04-15T22:56:00-07:00",
    },
    {
      id: "task-3",
      title: "Connect live GitHub data later",
      status: "open",
      issueNumber: null,
      owner: "director",
      updatedAt: "2026-04-15T22:50:00-07:00",
    },
  ],
  issues: [
    {
      number: 417,
      title: "Dashboard V3 should be issue-backed and truth-first",
      state: "open",
      labels: ["dashboard", "ops"],
      url: "https://github.com/bob-sec/issues/417",
      updatedAt: "2026-04-15T22:56:00-07:00",
    },
    {
      number: 412,
      title: "Clarify snapshot fallback behavior",
      state: "open",
      labels: ["dashboard", "safety"],
      url: "https://github.com/bob-sec/issues/412",
      updatedAt: "2026-04-15T22:49:00-07:00",
    },
    {
      number: 401,
      title: "Reduce noise in OpenClaw error stream",
      state: "closed",
      labels: ["observability"],
      url: "https://github.com/bob-sec/issues/401",
      updatedAt: "2026-04-15T21:15:00-07:00",
    },
  ],
  errors: [
    {
      id: "err-1",
      source: "OpenClaw gateway",
      message: "Telemetry socket unavailable, using snapshot data",
      severity: "warn",
      updatedAt: "2026-04-15T22:58:00-07:00",
    },
    {
      id: "err-2",
      source: "GitHub mirror",
      message: "No browser secret handling, fetches are snapshot-only in this scaffold",
      severity: "info",
      updatedAt: "2026-04-15T22:57:00-07:00",
    },
  ],
  events: [
    {
      id: "evt-1",
      kind: "sync",
      message: "Loaded local snapshot data for dashboard render",
      updatedAt: "2026-04-15T22:58:00-07:00",
    },
    {
      id: "evt-2",
      kind: "fallback",
      message: "Live sources are not claimed in this scaffold",
      updatedAt: "2026-04-15T22:58:00-07:00",
    },
  ],
};
